[package]
name = "runpack_repl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runpack = { path = "../runpack/runpack" }
runpack_obj = { path = "../runpack/runpack_obj" }
